### ISSUE TITLE
can't report if deploy success or not

### ISSUE THREAD

**Issue by winds6206** [markusressel/keel-telegram-bot#66]
**Describe the bug**
Hi 

I integrate keel and keel-telegram-bot, it's can send approval or reject message. 
when the pod is deployed successfully, telegram can't receive result success or failed.

Here is keel log
```
time="2022-03-15T06:19:51Z" level=info msg="approvals.manager: approved" identifier="deployment/default/helloworld:latest"
time="2022-03-15T06:19:51Z" level=error msg="could not send notification via notifier" error="Post \"http://keel-telegram-bot.keel.svc.cluster.local:5000/\": dial tcp: lookup keel-telegram-bot.keel.svc.cluster.local: device or resource busy" notification name="update resource" sender name=webhook
time="2022-03-15T06:19:51Z" level=info msg="waiting before retrying to send notification" attempts=2 duration=1s max attempts=10 notification name="update resource" sender name=webhook
```  

I think keel-telegram-bot can't proccess keel result message?

**Comment by markusressel** [comment]
Hi @winds6206,

the keel-telegram-bot logs would be more interesting if you think that it might not be able to handle the message. But it is more likely that keel cannot reach the webserver running on the keel-telegram-bot container.

**Comment by winds6206** [comment]
I resolve this problem .. but it's so weird.

I separate deploy keel & keel-telegram-bot in the same namespace(keel) , then set webhook url of keel-telegram-bot in keel config like this 
```
- name: WEBHOOK_ENDPOINT
   value: "http://keel-telegram-bot.keel.svc.cluster.local:5000"
```
Using FQDN will cannot reach the webserver, when I change the value as below
```
- name: WEBHOOK_ENDPOINT
   value: "http://keel-telegram-bot:5000"
```
It's working .

**Comment by markusressel** [comment]
Since you got it working, I will close this.
